dig = input('Digite algo ')
print('O tipo primitivo dese valor é {}'.format(type(dig)))
print('Só tem espaços? {}' .format(dig.isspace()))
print('É um número? {}' .format(dig.isnumeric()))
print('É alfabético? {}'.format(dig.isalpha()))
print('É alfanumérico? {}'.format(dig.isalnum()))
print('Está em maiuscúlas? {}'.format(dig.isupper()))
print('Está em minúsculas? {}'.format(dig.islower()))
print('Está capitalizada? {}'.format(dig.istitle()))
